def get_template(config):
    """
    Génère le router FastAPI pour le CRUD
    """
    model_name = config["model_name"]
    ModelName = config["ModelName"]
    app_name = config["app_name"]

    return f'''"""
FastAPI router for {ModelName}
Generated by FastWizard
"""
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from app.database import get_db
from app.domains.{app_name} import services as {model_name}_services
from app.domains.{app_name}.schemas import {ModelName}, {ModelName}Create, {ModelName}Update

router = APIRouter(prefix="/{model_name}s", tags=["{ModelName}"])

@router.get("/", response_model=list[{ModelName}])
def read_all(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    return {model_name}_services.get_{model_name}(db, skip=skip, limit=limit)

@router.get("/{{id}}", response_model={ModelName})
def read_one(id: int, db: Session = Depends(get_db)):
    obj = {model_name}_services.get_{model_name}_by_id(db, id=id)
    if not obj:
        raise HTTPException(status_code=404, detail="{ModelName} not found")
    return obj

@router.post("/", response_model={ModelName})
def create(obj_in: {ModelName}Create, db: Session = Depends(get_db)):
    return {model_name}_services.create_{model_name}(db, obj_in)

@router.put("/{{id}}", response_model={ModelName})
def update(id: int, obj_in: {ModelName}Update, db: Session = Depends(get_db)):
    db_obj = {model_name}_services.get_{model_name}_by_id(db, id=id)
    if not db_obj:
        raise HTTPException(status_code=404, detail="{ModelName} not found")
    return {model_name}_services.update_{model_name}(db, db_obj, obj_in)

@router.delete("/{{id}}")
def delete(id: int, db: Session = Depends(get_db)):
    db_obj = {model_name}_services.get_{model_name}_by_id(db, id=id)
    if not db_obj:
        raise HTTPException(status_code=404, detail="{ModelName} not found")
    return {model_name}_services.delete_{model_name}(db, db_obj)
'''
