def get_template(config):
    """
    Génère le modèle SQLAlchemy pour le CRUD
    config doit contenir : ModelName, model_name, fields
    """
    fields_code = ""
    type_mapping = {
        "str": "String",
        "int": "Integer",
        "float": "Float",
        "bool": "Boolean",
        "datetime": "DateTime"
    }

    for name, typ in config.get("fields", {}).items():
        col_type = type_mapping.get(typ, "String")
        fields_code += f"    {name} = Column({col_type}, nullable=True)\n"

    return f'''"""
SQLAlchemy model for {config["ModelName"]}
Generated by FastWizard
"""
from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime
from app.database import Base

class {config["ModelName"]}(Base):
    __tablename__ = "{config["model_name"]}s"

    id = Column(Integer, primary_key=True, index=True)
{fields_code}'''
