def get_template(config):
    """
    Génère les schemas Pydantic pour le CRUD
    """
    fields_code = ""
    type_mapping = {
        "str": "str",
        "int": "int",
        "float": "float",
        "bool": "bool",
        "datetime": "datetime"
    }

    for name, typ in config.get("fields", {}).items():
        fields_code += f"    {name}: {type_mapping.get(typ, 'str')} | None = None\n"

    return f'''"""
Pydantic schemas for {config["ModelName"]}
Generated by FastWizard
"""
from pydantic import BaseModel
from datetime import datetime

class {config["ModelName"]}Base(BaseModel):
{fields_code}

class {config["ModelName"]}Create({config["ModelName"]}Base):
    pass

class {config["ModelName"]}Update({config["ModelName"]}Base):
    pass

class {config["ModelName"]}InDBBase({config["ModelName"]}Base):
    id: int

    class Config:
        orm_mode = True

class {config["ModelName"]}({config["ModelName"]}InDBBase):
    pass
'''
