def get_template(config):
    """
    Génère les fonctions CRUD pour le modèle
    """
    model_name = config["model_name"]
    ModelName = config["ModelName"]

    return f'''"""
CRUD services for {ModelName}
Generated by FastWizard
"""
from sqlalchemy.orm import Session
from app.domains.{config["app_name"]}.model import {ModelName}
from app.domains.{config["app_name"]}.schemas import {ModelName}Create, {ModelName}Update

def get_{model_name}(db: Session, skip: int = 0, limit: int = 100):
    return db.query({ModelName}).offset(skip).limit(limit).all()

def get_{model_name}_by_id(db: Session, id: int):
    return db.query({ModelName}).filter({ModelName}.id == id).first()

def create_{model_name}(db: Session, obj_in: {ModelName}Create):
    db_obj = {ModelName}(**obj_in.dict())
    db.add(db_obj)
    db.commit()
    db.refresh(db_obj)
    return db_obj

def update_{model_name}(db: Session, db_obj: {ModelName}, obj_in: {ModelName}Update):
    for field, value in obj_in.dict(exclude_unset=True).items():
        setattr(db_obj, field, value)
    db.commit()
    db.refresh(db_obj)
    return db_obj

def delete_{model_name}(db: Session, db_obj: {ModelName}):
    db.delete(db_obj)
    db.commit()
'''
