def get_template(config):
    return f'''"""
Redis cache configuration and helper functions.
Automatically generated by FastWizard 🧙‍♂️
"""

from typing import Optional
from fastapi import FastAPI
from redis.asyncio import Redis
from contextlib import asynccontextmanager

REDIS_URL = "{config.get('redis_url', 'redis://redis:6379/0')}"
redis_client: Optional[Redis] = None


async def get_redis() -> Redis:
    """Return an active Redis connection (create one if needed)."""
    global redis_client
    if redis_client is None:
        redis_client = Redis.from_url(
            REDIS_URL,
            encoding="utf-8",
            decode_responses=True
        )
    return redis_client


async def close_redis():
    """Close the Redis connection gracefully."""
    global redis_client
    if redis_client:
        await redis_client.aclose()
        redis_client = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """FastAPI lifespan context to initialize and close Redis."""
    global redis_client
    redis_client = Redis.from_url(
        REDIS_URL,
        encoding="utf-8",
        decode_responses=True
    )
    print("✅ Redis cache connected")
    try:
        yield
    finally:
        await close_redis()
        print("🛑 Redis cache closed")
'''
