def get_template(config):
    return f'''"""
Valkey cache configuration and helper functions.
Automatically generated by FastWizard 🧙‍♂️
"""

from typing import Optional
from fastapi import FastAPI
from redis.asyncio import Redis  # Valkey compatible Redis protocol
from contextlib import asynccontextmanager

VALKEY_URL = "{config.get('valkey_url', 'redis://valkey:6379/0')}"
valkey_client: Optional[Redis] = None


async def get_valkey() -> Redis:
    """Return an active Valkey connection (create one if needed)."""
    global valkey_client
    if valkey_client is None:
        valkey_client = Redis.from_url(
            VALKEY_URL,
            encoding="utf-8",
            decode_responses=True
        )
    return valkey_client


async def close_valkey():
    """Close the Valkey connection gracefully."""
    global valkey_client
    if valkey_client:
        await valkey_client.aclose()
        valkey_client = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """FastAPI lifespan context to initialize and close Valkey."""
    global valkey_client
    valkey_client = Redis.from_url(
        VALKEY_URL,
        encoding="utf-8",
        decode_responses=True
    )
    print("✅ Valkey cache connected")
    try:
        yield
    finally:
        await close_valkey()
        print("🛑 Valkey cache closed")
'''
