def get_template(config):
    return f'''"""
WebSocket module for FastAPI.
Automatically generated by FastWizard 🧙‍♂️
"""

from fastapi import WebSocket, WebSocketDisconnect
from typing import List, Dict

class ConnectionManager:
    """Manage WebSocket connections and rooms."""
    def __init__(self):
        self.active_connections: Dict[str, List[WebSocket]] = {{}}  # room_name -> connections

    async def connect(self, websocket: WebSocket, room: str):
        await websocket.accept()
        if room not in self.active_connections:
            self.active_connections[room] = []
        self.active_connections[room].append(websocket)
        print("✅ Client connected to room '{{room}}'")

    def disconnect(self, websocket: WebSocket, room: str):
        if room in self.active_connections and websocket in self.active_connections[room]:
            self.active_connections[room].remove(websocket)
            print("❌ Client disconnected from room '{{room}}'")

    async def broadcast(self, message: str, room: str):
        """Send message to all clients in a room."""
        if room in self.active_connections:
            for connection in self.active_connections[room]:
                await connection.send_text(message)

# Singleton manager
manager = ConnectionManager()

# Example WebSocket endpoint
async def websocket_endpoint(websocket: WebSocket, room: str):
    """A WebSocket endpoint for a specific room."""
    await manager.connect(websocket, room)
    try:
        while True:
            data = await websocket.receive_text()
            # Echo the message to all clients in the room
            await manager.broadcast(f"[{{room}}] {{data}}", room)
    except WebSocketDisconnect:
        manager.disconnect(websocket, room)
'''
