def get_template(config):
    return f'''"""
WebSocket router for FastAPI.
Automatically generated by FastWizard 🧙‍♂️
"""

from fastapi import APIRouter, WebSocket
from app.core.websocket import websocket_endpoint

router = APIRouter()

@router.websocket("/room/{{room}}")
async def ws_room(websocket: WebSocket, room: str):
    await websocket_endpoint(websocket, room)
'''
